force-app/main/default/objects/Account_Category__c/Account_Category__c.object-meta.xml
<CustomObject>
    <label>Account Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category_Section_Filter__c/Category_Section_Filter__c.object-meta.xml
<CustomObject>
    <label>Category Section Filter</label>
    <nameField>
        <label>API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category Section Filter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category_Section_Filter__c/fields/Account_Category__c.field-meta.xml
<CustomField>
    <fullName>Account_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Category</label>
    <referenceTo>Account_Category__c</referenceTo>
    <relationshipLabel>Category Section Filter</relationshipLabel>
    <relationshipName>Category_Section_Filter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category_Section_Filter__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Equal To</fullName>
            </value>
            <value>
                <fullName>Not Equal To</fullName>
            </value>
            <value>
                <fullName>Greater Than</fullName>
            </value>
            <value>
                <fullName>Lesser Than</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CategorySectionFilterTriggerHelper.cls
public class CategorySectionFilterTriggerHelper {
    public static void validatingDuplicateFilters(List<Category_Section_Filter__c>categoryFilterList){
        set<String> categorySet = new Set<String>();
        for(Category_Section_Filter__c ctSecRec : categoryFilterList){
            if(ctSecRec.Value__c != null){
                categorySet.add(ctSecRec.Value__c);
            }
        }
        Map<String,Category_Section_Filter__c>catSecMap =new Map<String,Category_Section_Filter__c>();
        for(Category_Section_Filter__c ctSecRec: [Select Id,Account_Category__c, Value__c, Operator__c from Category_Section_Filter__c where Value__c IN : categorySet]){
            if(ctSecRec.Value__c != null){
                catSecMap.put(ctSecRec.Value__c, ctSecRec);
            }
        }
        for(Category_Section_Filter__c catSecRec:categoryFilterList){
            if(catSecMap.ContainsKey(catSecRec.Value__c) && (catSecMap.get(catSecRec.Value__c).Operator__c == catSecRec.Operator__c 
                                                             && catSecMap.get(catSecRec.Value__c).Account_Category__c == catSecRec.Account_Category__c)){
                catSecRec.addError('This filter value exsist');
            }
        }
    }
    public static void validatingDuplicateFiltersWhenUpdate(List<Category_Section_Filter__c>categoryFilterList, Map<Id,Category_Section_Filter__c>oldMap){
        set<String> categorySet = new Set<String>();
        for(Category_Section_Filter__c ctSecRec : categoryFilterList){
            if(ctSecRec.Value__c != null &&(oldMap.get(ctSecRec.Id).Value__c != ctSecRec.Value__c)){
                categorySet.add(ctSecRec.Value__c);
            }
        }
        Map<String,Category_Section_Filter__c>catSecMap =new Map<String,Category_Section_Filter__c>();
        for(Category_Section_Filter__c ctSecRec: [Select Id,Account_Category__c, Value__c,Operator__c  from Category_Section_Filter__c where Value__c IN : categorySet]){
            if(ctSecRec.Value__c != null){
                catSecMap.put(ctSecRec.Value__c, ctSecRec);
            }
        }
        for(Category_Section_Filter__c catSecRec:categoryFilterList){
            if(catSecMap.ContainsKey(catSecRec.Value__c) && (catSecMap.get(catSecRec.Value__c).Operator__c == catSecRec.Operator__c 
                                                             && catSecMap.get(catSecRec.Value__c).Account_Category__c == catSecRec.Account_Category__c)){
                catSecRec.addError('This filter value exsist');
            }
        }
    }
}