force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Category__c/Account_Category__c.object-meta.xml
<CustomObject>
    <label>Account Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Category__c/fields/Default_Category__c.field-meta.xml
<CustomField>
    <fullName>Default_Category__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Category</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Category_Section_Filter__c/Category_Section_Filter__c.object-meta.xml
<CustomObject>
    <label>Category Section Filter</label>
    <nameField>
        <label>API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category Section Filter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category_Section_Filter__c/fields/Account_Category__c.field-meta.xml
<CustomField>
    <fullName>Account_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Category</label>
    <referenceTo>Account_Category__c</referenceTo>
    <relationshipLabel>Category Section Filter</relationshipLabel>
    <relationshipName>Category_Section_Filter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category_Section_Filter__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Equal To</fullName>
            </value>
            <value>
                <fullName>Not Equal To</fullName>
            </value>
            <value>
                <fullName>Greater Than</fullName>
            </value>
            <value>
                <fullName>Lesser Than</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountCategoryFilterBatch.cls
public class AccountCategoryFilterBatch implements Database.Batchable<sObject>, Database.stateful {
    public List<sObject> start(Database.BatchableContext BC){
        List<sObject> sob = new List<sObject>();
        sob.addAll([Select id, Credit_Limit__c, Annual_Revenue__c, Category__c from Account__c where Credit_Limit__c !=null AND Annual_Revenue__c != null  ]);
        sob.addAll([Select id,Name, Account_Category__r.Name,Account_Category__r.Active__c, Account_Category__r.Default_Category__c, Operator__c, Value__c from Category_Section_Filter__c]);
        return sob;
    } 
    public void Execute(Database.BatchableContext Bc, List<sObject> listOfRecords){
        Map<Decimal,Map<Decimal,List<Account__c>>> accMap = new Map<Decimal, Map<Decimal,List<Account__c>>>();
        Map<string,List<Category_Section_Filter__c>> CategoryMap = new Map<string,List<Category_Section_Filter__c>>();
        Map<String,List<Category_Section_Filter__c>> AnnualRevenueMap = new Map<String,List<Category_Section_Filter__c>>();
        Map<String,Map<String,String>> categoryNewMap = new Map<String,Map<String,String>>();
        List<Category_Section_Filter__c> csfList = new List<Category_Section_Filter__c>();
        string defaultCategory = '';
        for(sObject sob: listOfRecords){
            switch on sob {
                when Category_Section_Filter__c csf{
                    csfList.add(csf);
                    if((csf.Name =='Annual Revenue' && categoryNewMap.containsKey(csf.Value__c))){
                        
                    }
                }
                When Account__c accRec{
                   string accString = accRec.Annual_Revenue__c+' '+accRec.Credit_Limit__c;
                }
            }
        }
        for(Category_Section_Filter__c csf: csfList){
        
    }
    }public void finish(Database.BatchableContext Bc){
    }
}