force-app/main/default/objects/Account__c/Account__c.object-meta.xml
<CustomObject>
    <label>Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SILVER</fullName>
            </value>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>PLATINUM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account__c/fields/Sales_Representative__c.field-meta.xml
<CustomField>
    <fullName>Sales_Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Representative</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Category__c/Account_Category__c.object-meta.xml
<CustomObject>
    <label>Account Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category_Section_Filter__c/Category_Section_Filter__c.object-meta.xml
<CustomObject>
    <label>Category Section Filter</label>
    <nameField>
        <label>API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category Section Filter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category_Section_Filter__c/fields/Account_Category__c.field-meta.xml
<CustomField>
    <fullName>Account_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Category</label>
    <referenceTo>Account_Category__c</referenceTo>
    <relationshipLabel>Category Section Filter</relationshipLabel>
    <relationshipName>Category_Section_Filter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category_Section_Filter__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Equal To</fullName>
            </value>
            <value>
                <fullName>Not Equal To</fullName>
            </value>
            <value>
                <fullName>Greater Than</fullName>
            </value>
            <value>
                <fullName>Lesser Than</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountCategoryUpdateBatch.cls
public class AccountCategoryUpdateBatch implements Database.Batchable<sObject>{
    public database.QueryLocator start (Database.BatchableContext Bc){
        return Database.getQueryLocator('SELECT Id,Annual_Revenue__c,Category__c,Credit_Limit__c,Sales_Representative__c FROM Account__c');
        //return Database.getQueryLocator('Select Id,Account_Category__c,Account_Category__r.Name, Value__c,Operator__c  from Category_Section_Filter__c');
    }public void execute(Database.BatchableContext Bc, List<sObject>listOfRecords){
        List<Account__c>AccountList = (List<Account__c>)listOfRecords;
        List<Category_Section_Filter__c> categorySctnLst = [SELECT Account_Category__c,Name,Operator__c,Value__c FROM Category_Section_Filter__c]; 
        Map<Decimal, Category_Section_Filter__c> ctSecMap = new Map<Decimal, Category_Section_Filter__c>();
        for(Category_Section_Filter__c ctRec:categorySctnLst){
            ctSecMap.put(integer.valueOf(ctRec.Value__c), ctRec);
        }
        List<Account__c> accListUpdate = new List<Account__c>();
        for(Account__c accRec : AccountList){
            if(accRec.Credit_Limit__c >= 1000 && accRec.Credit_Limit__c < 10000 && accRec.Annual_Revenue__c == 100000){
                accRec.Category__c = 'Gold';
                accListUpdate.add(accRec);
            }else if(accRec.Credit_Limit__c >= 10000 && accRec.Credit_Limit__c < 20000 && accRec.Annual_Revenue__c == 200000){
                accRec.Category__c = 'Silver';
                accListUpdate.add(accRec);
            }else if(accRec.Credit_Limit__c > 20000 && accRec.Annual_Revenue__c == 300000){
                accRec.Category__c = 'Platinum';
                accListUpdate.add(accRec);
            }
        }
        if(!accListUpdate.isEmpty()){
            update  accListUpdate;
        }
    }public void finish(Database.BatchableContext BC){
        
    }
    
}